export const siteData = {
    general: {
        siteName: "ITSS",
        tagline: "Total Office Automation Solutions",
        contactEmail: "Itss.facilities@rediffmail.com",
        contactPhone: "+91 97183 71994, +91 99537 90266",
        address: "F-161, 2nd floor, Dilshad colony, Delhi 110095",
        logo: "/logo_v2.png",
    },
    home: {
        hero: {
            headline: "Information Technology Solution & Services",
            subheadline: "Providing total office automation solutions for our customers.",
            ctaPrimary: "Our Services",
            ctaSecondary: "About Us",
        },
        aboutSummary: {
            title: "Who We Are",
            content: "ITSS was established in the year 2012 with a sole aim of providing total office automation solutions for its customers. We believe that selling does not end with supplying the goods but it begins with it.",
        },
    },
    about: {
        overview: "ITSS was established in the year 2012...",
        mission: "To provide robust and quick IT services...",
        vision: "To become the leading IT solution provider...",
    },
    services: [
        {
            id: "interior-decorators",
            title: "Interior Decorators",
            description: "Interior decorators bring their creative flair to rooms, creating homes that are harmonious and customized by striking a balance between usefulness and aesthetics.",
        },
        {
            id: "turnkey-project",
            title: "Turnkey Project",
            description: "A \"turnkey project\" delivers a fully functional result to the client, covering design, construction, and implementation without needing additional client involvement.",
        },
        {
            id: "space-planner",
            title: "Space Planner",
            description: "We specialize in thoughtful interior planning for optimal aesthetics, flow, and functionality, tailored to meet our clients' needs and preferences.",
        },
        {
            id: "civil-contractor",
            title: "Civil Contractor",
            description: "We utilize civil engineering construction projects like buildings, bridges, roads, and infrastructure.",
        },
        {
            id: "chair-sofa-repair",
            title: "Chair & Sofa Repair",
            description: "Our specialty is chair and couch repair services, giving your furniture its original comfort and style again.",
        },
    ],
    contact: {
        formTitle: "Get In Touch",
        formDescription: "We would love to hear from you. Please fill out the form below.",
    },
    clients: [
        { id: 1, name: "91 Springboard", category: "Enterprise", logo: "/clients/91springboard.png" },
        { id: 2, name: "AECOM", category: "Enterprise", logo: "/clients/aecom.png" },
        { id: 3, name: "Blinkit", category: "Enterprise", logo: "/clients/blinkit.png" },
        { id: 4, name: "Gati", category: "Logistics", logo: "/clients/gati.png" },
        { id: 5, name: "Hitachi", category: "Enterprise", logo: "/clients/hitachi.png" },
        { id: 6, name: "Hilton", category: "Hospitality", logo: "/clients/hilton.png" },
        { id: 7, name: "Leader", category: "Manufacturing", logo: "/clients/leader.png" },
        { id: 8, name: "Paytm", category: "Fintech", logo: "/clients/paytm.png" },
        { id: 9, name: "Punjab Grill", category: "Hospitality", logo: "/clients/punjab_grill.png" },
        { id: 10, name: "Samsung SDS", category: "Technology", logo: "/clients/samsung_sds.png" },
        { id: 11, name: "Shoppers Stop", category: "Retail", logo: "/clients/shoppers_stop.png" },
        { id: 12, name: "SRF", category: "Manufacturing", logo: "/clients/srf.png" },
        { id: 13, name: "TATA 1mg", category: "Healthcare", logo: "/clients/tata_1mg.png" },
        { id: 14, name: "TCI Express", category: "Logistics", logo: "/clients/tci_express.png" },
        { id: 15, name: "Zomato", category: "Technology", logo: "/clients/zomato.png" },
        { id: 16, name: "Wagh Bakri", category: "Retail", logo: "/clients/wagh_bakri.png" },
        { id: 17, name: "Battery Smart", category: "Technology", logo: "/clients/battery_smart.png" },
        { id: 18, name: "Itochu", category: "Enterprise", logo: "/clients/itochu.png" },
        { id: 19, name: "Nagarro", category: "Technology", logo: "/clients/nagarro.png" },
        { id: 20, name: "Allianz", category: "Finance", logo: "/clients/allianz.png" },
        { id: 21, name: "Incuspaze", category: "Real Estate", logo: "/clients/incuspaze.png" },
        { id: 22, name: "Shriram Automall", category: "Automotive", logo: "/clients/shriram_automall.png" },
        { id: 23, name: "Benetton", category: "Retail", logo: "/clients/benetton.png" },
        { id: 24, name: "Godrej", category: "Manufacturing", logo: "/clients/godrej.png" },
        { id: 25, name: "SISL", category: "Services", logo: "/clients/sisl.png" },
        { id: 26, name: "Sharekhan", category: "Finance", logo: "/clients/sharekhan.png" },
        { id: 27, name: "Hughes Systique", category: "Technology", logo: "/clients/hughes_systique.png" },
        { id: 28, name: "The Indian Express", category: "Media", logo: "/clients/indian_express.png" },
        { id: 29, name: "Infogain", category: "Technology", logo: "/clients/infogain.png" },
        { id: 30, name: "MPS Limited", category: "Publishing", logo: "/clients/mps_limited.png" },
        { id: 31, name: "V5 Global", category: "Services", logo: "/clients/v5_global.png" },
        { id: 32, name: "Adani", category: "Enterprise", logo: "/clients/adani.png" },
        { id: 33, name: "Avitech", category: "Technology", logo: "/clients/avitech.png" },
        { id: 34, name: "Bollhoff", category: "Manufacturing", logo: "/clients/bollhoff.png" },
        { id: 35, name: "Domino's Pizza", category: "Food & Beverage", logo: "/clients/dominos.png" },
        { id: 36, name: "Sodexo", category: "Services", logo: "/clients/sodexo.png" },
        { id: 37, name: "The Lodhi", category: "Hospitality", logo: "/clients/the_lodhi.png" },
        { id: 38, name: "Sarvodaya Healthcare", category: "Healthcare", logo: "/clients/sarvodaya_healthcare.png" },
        { id: 39, name: "Exicom", category: "Technology", logo: "/clients/exicom.png" },
        { id: 40, name: "Hines", category: "Real Estate", logo: "/clients/hines.png" },
        { id: 41, name: "EXL", category: "Technology", logo: "/clients/exl.png" },
        { id: 42, name: "MCM", category: "Services", logo: "/clients/mcm.png" },
        { id: 43, name: "CSC", category: "Services", logo: "/clients/csc.png" },
        { id: 44, name: "Denave", category: "Services", logo: "/clients/denave.png" },
        { id: 45, name: "SMC Insurance", category: "Finance", logo: "/clients/smc_insurance.png" },
        { id: 46, name: "Dr Lal PathLabs", category: "Healthcare", logo: "/clients/dr_lal_pathlabs.png" },
        { id: 47, name: "7 Star", category: "Manufacturing", logo: "/clients/7_star.png" },
        { id: 48, name: "Barclays", category: "Finance", logo: "/clients/barclays.png" },
    ],
};
